-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQdqGfyxzBvH+vAQF
zogYFcWJCh7NBZfwv93rq/pb5QagCgYIKoZIzj0DAQehRANCAATzbBiKO6v+e216
Eyb6ul5v4b/U03gz8TmzdsgmsSQiT2daD4uA5dESBAUPe0ttVd1YSFjdIeDoEpfR
He3AgcXB
-----END PRIVATE KEY-----